config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'
  resources :bookings, except: [:show]

  devise_for :users
  get 'home/index'
  resources :home, except: [:show]
  root 'home#index' # pagina inicial

end

app/models/booking.rb
class Booking < ActiveRecord::Base

  belongs_to :user

  attr_accessor :current_user

  validates_presence_of :date, :hour

  validate :ownership, on: [:update]
  validate :not_past, on: [:create, :update]
  validate :free, on: [:create, :update]

  before_destroy :ownership #Nao funciona
  before_destroy :not_past #Nao funciona

  scope :order_by_date, -> { order(:date, :hour) }
  scope :in_range, ->(x) { where('date BETWEEN ? AND ?', x, x + 5.day)}

  private

  def ownership
    errors.add(:user, 'Não é possível alterar/excluir a reserva de outro usuário') if user != current_user
  end

  def not_past
    if date.nil?
      errors.add(:date, 'Impossível calcular a data vazia')
      return
    end
    errors.add(:date, 'Não é possível criar/alterar/excluir uma reserva com data passada') if date.past?
  end

  def free
    booking = Booking.where(date: date, hour: hour).where.not(id: id)
    restrict = 0
    booking.each do |f|
      restrict = f.id
    end
    errors.add(:date, 'Essa data hora já está reservada') unless restrict.zero?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	before_action :authenticate_user!
  before_action :set_booking, only: [:edit, :update, :destroy]


  def index
  	@bookings = Booking.all.order_by_date
  end

  def show

  end

  def new
    @booking = Booking.new
  end

  def edit

  end

  def create
  	@booking = Booking.new(params_booking)
    @booking.user = current_user

  	if @booking.save
  		redirect_to bookings_path, notice: "Reserva cadastrada com sucesso!"
  	else
  		render :new
  	end
  end

  def update
    @booking.current_user = current_user
    if @booking.update(params_booking)
    	redirect_to bookings_path, notice: "Reserva atualizada com sucesso!"
    else
    	render :edit
    end
  end

  def destroy
    @booking.current_user = current_user
    if @booking.destroy
      redirect_to bookings_path, notice: "A Reserva foi excluída com sucesso!"
    else
      render :index
    end
  end

  private
  def set_booking
    @booking = Booking.find(params[:id])
  end

  def params_booking
    params.require(:booking).permit(:description, :user_id, :hour, :date)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!


  def new
    respond_to do |format|
      format.html {}
      format.js { render '/home/new.js.erb' }
    end
  end


  def index

    @weekdays = ["Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira"]
    @timetables = ["08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00"]

    if params[:new_day].present? && ! params[:new_day].blank?
      @date = params[:new_day].to_date
    else
      @date = Time.current.strftime('%d/%m/%Y').to_date
    end

    if @date.monday?
      add = 0
    elsif @date.tuesday?
      add = 1
    elsif @date.wednesday?
      add = 2
    elsif @date.thursday?
      add = 3
    elsif @date.friday?
      add = 4
    elsif @date.saturday?
      @date = @date + 2.days
      add = 0
    elsif @date.sunday?
      @date = @date + 1.days
      add = 0
    end

    @iniDate = (@date - add.days)

    @dates = []
    i = 0
    @weekdays.each do |_day|
      @dates << (@iniDate + i.days).strftime('%d/%m/%Y')
      i += 1
    end

    @appointments = Booking.in_range(@date).order_by_date

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bookings/edit.html.erb
<h1>Editar Reserva</h1>

<%= render 'bookings/shared/form', booking: @booking %>

app/views/bookings/index.html.erb
<header class="bg-primary text-white">
  <div class="container text-center">
    <h1>Reservas Sala de Reunião</h1>
  </div>
</header>

<p id="notice"><%= notice %></p>

<section id="services" class="bg-light">
<div class="container">
  <div class="row">
    <div class="col-lg-8 mx-auto">

      <table>
        <thead>
          <tr>
            <th><h2>Data</h2></th>
            <th><h2>Hora</h2></th>
            <th><h2>Descrição</h2></th>
            <th><h2>Usuário</h2></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @bookings.each do |booking| %>
            <tr>
              <td style="padding: 20px;" ><%= booking.date %></td>
              <td style="padding: 20px;" ><%= booking.hour %></td>
              <td style="padding: 20px;" ><%= booking.description %></td>
              <td style="padding: 20px;"><%= booking.user.email %></td>
              <td style="padding: 20px;"><%= link_to 'Editar', edit_booking_path(booking) %></td>

              <td style="padding: 20px;"><%= link_to 'Excluir', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to "#{t('buttons.new')}", new_booking_path, class: 'btn btn-primary btn-lg white' %>
    </div>
  </div>
</div>
</section>

app/views/bookings/new.html.erb
<h1>Nova Reserva</h1>

<%= render 'bookings/shared/form', booking: @booking %>

app/views/bookings/shared/_form.html.erb
<header class="bg-primary text-white">
  <div id="titulo" class="container text-center" >
    <h1>Reservar Sala de Reunião</h1>
  </div>
</header>
<section id="services" class="bg-light">
<div class="container">
  <div class="row">
    <div class="col-lg-8 mx-auto">

      <%= form_for([@booking],  html: { multipart: true }) do |f| %>
        <% if booking.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(booking.errors.count, "error") %> prohibited this appointment from being saved:</h2>

            <ul>
              <% booking.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="row">
          <div class="col-xs-6">
            <div class="form-group">
              <%= f.label :date %>
              <%= f.date_field :date, class: "datepicker form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-6">
            <div class="form-group">
              <%= f.label :hour %>
              <%= f.select :hour , [['08:00', '08:00'], ['09:00', '09:00'], ['10:00', '10:00'], ['11:00', '11:00'], ['12:00', '12:00'], ['13:00', '13:00'], ['14:00', '15:00'], ['16:00', '16:00'],['17:00', '17:00']], {}, { class: "form-control" }%>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-6">
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description,  rows: 5, class: "form-control"  %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <div class="form-group">
              <%= submit_tag "#{t('buttons.save')}", class: "btn btn-primary btn-lg white"  %>

              <%= link_to "#{t('buttons.back')}", bookings_path, class: 'btn btn-primary btn-lg white' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</section>

app/views/home/index.html.erb
<header class="bg-primary text-white">
<div class="container text-center">
  <h1>Agenda Sala de Reunião</h1>
</div>
</header>

<p id="notice"><%= notice %></p>

<section id="services" class="bg-light">
<div class="container">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <div class="page-header">
        <div class="row">
          <div class="col-sm-12 col-lg-12">
          <%= form_tag home_index_path, method: :get do %>
            <div class="row">
              <%= date_field_tag :new_day, value: Time.current, class: 'date-field' %>
              <%= submit_tag 'Pesquisar', class: 'btn btn-primary btn-lg white' %>
            <% end %>
          </div>
        </div>
        <div class="row" id="calendar">
          <div class="col-sm-12 col-lg-12">
            <table class="table table-striped">
              <thead class="thead-dark">
                <th>Horário</th>
                <% @weekdays.each_with_index do |day, ind| %>
                   <input type="hidden" id="base-date" value=<%=@dates[ind]%> >
                  <th scope="col"> <%= "#{day} - #{@dates[ind]}" %></th>
                <% end %>
              </thead>
              <tbody>
                <% @timetables.each do |hour| %>
                  <tr>
                    <th style="background-color:#424242;color:white;"> <%="#{hour}"%></th>
                    <td>
                      <%= render partial: 'home/shared/appointments', locals: {num: 0, hour: hour} %>
                    </td>
                    <td>
                      <%= render partial: 'home/shared/appointments', locals: {num: 1, hour: hour} %>
                    </td>
                    <td>
                      <%= render partial: 'home/shared/appointments', locals: {num: 2, hour: hour} %>
                    </td>
                    <td>
                      <%= render partial: 'home/shared/appointments', locals: {num: 3, hour: hour} %>
                    </td>
                    <td>
                      <%= render partial: 'home/shared/appointments', locals: {num: 4, hour: hour} %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/home/shared/_appointments.html.erb
<% nothing = true %>
<% @appointments.each do |app| %>
  <% if app.date.strftime('%d/%m/%Y') ==  @dates[num] and app.hour == hour %>
    Reservado <br> <%= app.user.email %>
    <i class="fa fa-eye"></i>
    <% if app.user == current_user%>
      <%= link_to app, method: :delete, data: { confirm: 'Tem Certeza?' },  remote: :true  do %>
        <i class="bi bi-calendar-x-fill">X</i>
      <% end %>
    <% end %>

    <% nothing = false%>
  <% end %>
<% end %>
<% if nothing %>
  <i class="available" >Disponível</i>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>BookApp</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

</head>

<body id="page-top">
	<%= render partial: "layouts/shared/navigation" %>
  <%= yield %>
  <%= render partial: "layouts/shared/footer" %>
  <script>
    $.notify("Ola");
  </script>

</body>

</html>

app/views/layouts/shared/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
<div class="container">
  <p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p>
</div>
<!-- /.container -->
</footer>

app/views/layouts/shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <div class="container">
    <i class="navbar-brand js-scroll-trigger" >BookApp</i>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to home_index_path do %>
            <i class="nav-link js-scroll-trigger">Agenda</i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to bookings_index_path do %>
            <i class="nav-link js-scroll-trigger">Reserva</i>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <i class="nav-link js-scroll-trigger">
              Usuário: <%= current_user.email %>
            </i>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="nav-link js-scroll-trigger">Sair</i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>